name: Release
description: Release a new Docker image
inputs:
  major:
    description: Major version number
    required: true
  minor:
    description: Minor version number
    required: true
  patch:
    description: Patch version number
    required: true
  sha:
    description: Git SHA
    required: true
runs:
  using: composite
  steps:
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - uses: docker/build-push-action@v4
      with:
        push: true
        labels: |
          org.opencontainers.image.source = https://github.com/${{ github.repository }}
        tags: |
          ghcr.io/${{ github.repository }}:${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}
          ghcr.io/${{ github.repository }}:${{ inputs.major }}.${{ inputs.minor }}
          ghcr.io/${{ github.repository }}:${{ inputs.major }}
          ghcr.io/${{ github.repository }}:${{ github.sha }}
          ghcr.io/${{ github.repository }}:latest
