name: ci
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          labels: |
            org.opencontainers.image.source = https://github.com/${{ github.repository }}
          tags: |
            ghcr.io/${{ github.repository }}:master
            ghcr.io/${{ github.repository }}:${{ github.sha }}
