name: ci
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.GAR_RESION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.GAR_RESION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_NAME }}/main:latest
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_TOKEN }}
          export_default_credentials: true
      - run: |
          gcloud components install beta
          gcloud beta compute instance-groups managed rolling-action replace vm-group-${{ secrets.GCP_NAME }} --max-surge=0 --max-unavailable=1 --min-ready=0 --replacement-method=substitute --zone=${{ secrets.GCE_RESION }}
