name: Release

on:
  workflow_call:
    inputs:
      major:
        type: string
        required: true
      minor:
        type: string
        required: true
      patch:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      major:
        type: string
        required: true
      minor:
        type: string
        required: true
      patch:
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup | Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup | Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Setup | Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          labels: |
            org.opencontainers.image.source = https://github.com/${{ github.repository }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}
            ghcr.io/${{ github.repository }}:${{ inputs.major }}.${{ inputs.minor }}
            ghcr.io/${{ github.repository }}:${{ inputs.major }}
            ghcr.io/${{ github.repository }}:latest
